### ISSUE TITLE
appimage with --show-playground parameter

### ISSUE THREAD

**Issue by rcspam** [aferrero2707/gimp-appimage#12]
Hi and thank for the work.
I try to launch **gimp-git-2.10.1-20180428.glibc2.15-x86_64.AppImage** with "**--show-playground**" option, but it ended with:

```
$ gimp-git-2.10.1-20180428.glibc2.15-x86_64.AppImage --show-playground
...
...
d8d1eb009cdedaf34393c9eb5cf4d3d-le64.cache-7bin/gimp.bin: fatal error: Aborted
```

**Comment by aferrero2707** [comment]
Which Linux distribution are you using?

I just tried on debian testing, and I get no crash when passing the *--show-playground* option.

Does it run normally without this option?

**Comment by rcspam** [comment]
Hi aferrero,
Yes, it worked without --show-playground option...

Since this issue, i have upgrade the appimage to the last (20180504), it work but another problem is happened, it crash due to the copy of 2.8/2.9 plugins in 'GIMP-AppImage' config folder. I had to remove some plugins from it to make your appimage work. It was not a problem before. So....

**Comment by aferrero2707** [comment]
Binary plugins in the 'GIMP-AppImage' config folder are likely to give troubles, because they have been compiled in an environment different from the one bundled in the AppImage.

I am working on a solution to provide a large selection of GIMP plug-ins that are compatible with the AppImage package, but that's not ready yet.

Python and/or scheme plug-ins should work properly.

**Comment by rcspam** [comment]
Ok thanks for your work...
scm plugins work well.
But python plugins produced this error:
```
Traceback (most recent call last):
  File "********************.py", line 28, in <module>
    from gimpfu import *
  File "/tmp/.mount_8hYxRn/usr/lib/gimp/2.0/python/gimpfu.py", line 76, in <module>
    import gimp
ImportError: /tmp/.mount_8hYxRn/usr/lib/gimp/2.0/python/gimp.so: undefined symbol: PyUnicodeUCS2_SetDefaultEncoding
bin/gimp.bin: LibGimpBase-AVERTISSEMENT: gimp.bin: gimp_wire_read(): error
```

**Comment by aferrero2707** [comment]
This means that some work is still needed to improve the python plugins support... could you be so kind to open a new issue for this, just not to mix topics?

Thanks!

**Comment by rcspam** [comment]
it is done...
