### ISSUE TITLE
Check minimal glibc dependency

### ISSUE THREAD

**Issue by ghost** [aferrero2707/gimp-appimage#13]
Currently AppImage has name such as: `gimp-*.glibc2.15-x86_64.AppImage`

But some user reported that minimal requred glibc is 2.17, so check it and fix naming of AppImage's.

**Comment by hardcorp74** [comment]
On Centos 7
/tmp/.mount_P36kez/usr/bin/gimp.bin: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/.mount_P36kez/usr/optional/libstdc++/libstdc++.so.6)

**Comment by aferrero2707** [comment]
@Symbian9 @HarDX
All this should be fixed in the latest packages. Could you please check?

Thanks!

**Comment by hardcorp74** [comment]
> @Symbian9 
> ...Could you please check?

Thanks, all is ok now on 2.10.7
