### ISSUE TITLE
Opening images with relative paths fail

### ISSUE THREAD

**Issue by tribut** [aferrero2707/gimp-appimage#16]
The appimage apparently uses its working-directory to resolve relative paths:

~~~
$ gimp test/test.png
~~~

results in

~~~
Opening '/tmp/.mount_wnXhPY/usr/test/test.png' failed: Could not open '/tmp/.mount_wnXhPY/usr/test/test.png' for reading: No such file or directory
~~~

The paths should be resolved relative to the directory the appimage was actually called from.

**Comment by aferrero2707** [comment]
@tribut at least for the moment, the launcher script in the AppImage bundle needs to change the current folder to the root of the bundle, otherwise the bundled libraries and other files are not properly seen.

This means that you must include the full path of any input file passed from the command line.
In future we need to see if (and how) the change of working directory can be avoided, for example by defining paths using environment variables...

**Comment by samrocketman** [comment]
@aferrero2707 a recommendation.  The appimage script will be referenced by full path.  `$0` is the path of the binary.  I would recommend setting up `LD_LIBRARY_PATH` and `PATH`.  Those two are especially important for the runtime so that no change of directory is required (which won't mess up relative paths users use).

**Comment by aferrero2707** [comment]
Those environment variables are set already... you can inspect the launcher script [here](https://github.com/aferrero2707/gimp-appimage/blob/master/AppRun-gimp).

However this is not  always enough, as there are cases where for different reasons the '/usr' path is hard coded, and gets replaced with '././' by the appimage generation script.

**Comment by aferrero2707** [comment]
Those environment variables are set already... you can inspect the launcher script [here](https://github.com/aferrero2707/gimp-appimage/blob/master/AppRun-gimp).

However this is not  always enough, as there are cases where for different reasons the '/usr' path is hard coded, and gets replaced with '././' by the appimage generation script.

**Comment by probonopd** [comment]
> However this is not always enough, as there are cases where for different reasons the '/usr' path is hard coded, and gets replaced with '././' by the appimage generation script.

Question is whether with the help of the GIMP upstream developers, we could get a relocatable version compiled that does not need this hack.

Check
* https://github.com/GNOME/gimp/blob/master/libgimpbase/gimpreloc.c
* https://github.com/GNOME/gimp/blob/ce02f4ad0556c58ee8299b8aa7837a1e6a526226/build/windows/jhbuild/build.jhbuildrc#L136
* https://github.com/GNOME/gimp/blob/ce02f4ad0556c58ee8299b8aa7837a1e6a526226/INSTALL.in#L246-L249

```
--enable-binreloc.  When compiled for Linux with this option enabled,
     GIMP will be binary relocatable.  Plug-ins and data files will
     be searched relative to the gimp binary instead of in the paths
     defined at compile time.
```

Might also come in handy:
* https://github.com/GNOME/gimp/blob/ce02f4ad0556c58ee8299b8aa7837a1e6a526226/libgimpbase/gimpenv.c#L841

**Comment by aferrero2707** [comment]
@probonopd that's definitely the way to go. I will look into this as soon as I manage.

Thanks for the hints!

**Comment by samrocketman** [comment]
AWESOME!

**Comment by samrocketman** [comment]
@probonopd I’m going to update builds on https://build.gimp.org/ to use this feature.

**Comment by probonopd** [comment]
Well @samrocketman actually this brings me to an idea: If you could have builds on https://build.gimp.org/ that a) use this feature and b) are built on a build system that is no newer than the oldest still-supported LTS distributions (currently Ubuntu 14.04), then we may be able to use those build products and convert them into an AppImage pretty easily. (It's essentially what LibreOffice is doing - they don't actually build LibreOffice specially for the the AppImage, they merely repackage what they already compile...)

**Comment by aferrero2707** [comment]
@tribut @probonopd @samrocketman 
I have prepared a first version of a relocatable GIMP AppImage, which should correctly open images with relative paths passed from the command line.

The package can be found [here](https://github.com/aferrero2707/gimp-appimage/releases/download/continuous/gimp-git-2.10.2-20180605.glibc2.15-x86_64.AppImage). Could you please test it and give me feedback?

Thanks!

**Comment by tribut** [comment]
Except for larger fonts in the loading screen (see below), I could not find any problems/differences compared with `gimp-git-2.10.1-20180428.glibc2.15-x86_64.AppImage`. Opening images using relative paths works now.

![1](https://user-images.githubusercontent.com/719105/40996653-dc473274-68f1-11e8-8457-17ce31920723.png)

**Comment by aferrero2707** [comment]
I am closing this since the initial issue (opening files with relative paths from the command line) works now. I am still working on the fonts problems.
