### ISSUE TITLE
No Russian Lang in last gimp

### ISSUE THREAD

**Issue by hardcorp74** [aferrero2707/gimp-appimage#21]
GIMP_AppImage-git-2.10.7-withplugins-20180913-x86_64.AppImage - lang present

GIMP_AppImage-git-2.10.7-withplugins-20180921-x86_64.AppImage - no lang

**Comment by aferrero2707** [comment]
I have recently done some cleanup work on the contents of the AppImage, and it seems I have been too aggressive and deleted the GIMP locale translations.

They are now restored in the latest package (https://github.com/aferrero2707/gimp-appimage/releases/download/continuous/GIMP_AppImage-git-2.10.7-withplugins-20180923-x86_64.AppImage). Could you please check if you can select Russian again?

**Comment by hardcorp74** [comment]
All is ok now, you can close issue

**Comment by aferrero2707** [comment]
Thanks!
