### ISSUE TITLE
GIMP 2.10.8 released!

### ISSUE THREAD

**Issue by ghost** [aferrero2707/gimp-appimage#22]
- https://www.gimp.org/news/2018/11/08/gimp-2-10-8-released/

**Comment by aferrero2707** [comment]
@Symbian9 
The build for the 2.10.8 release is now available: https://github.com/aferrero2707/gimp-appimage/releases/download/continuous/GIMP_AppImage-release-2.10.8-withplugins-x86_64.AppImage
