### ISSUE TITLE
Missing menu icon under Ubuntu

### ISSUE THREAD

**Issue by aferrero2707** [aferrero2707/gimp-appimage#25]
The menu icon for the appimage package is missing Ubuntu Mate 18.04.1 (and probably other distributions as well).
Link to original notification: https://discuss.pixls.us/t/gimp-appimage-continuous-integration/1959/528?u=carmelo_drraw

**Comment by Lvaskz** [comment]
Hi,  have the same issue with linuxmint 19.1 . Some progress about it?
Gimp appimage is very nice

**Comment by aferrero2707** [comment]
@Lvaskz this should be fixed in the latest packages. Could you please confirm?

Thanks!

**Comment by Lvaskz** [comment]
Hi, It is working well now in ubuntu 18.04.2
