### ISSUE TITLE
New AppImage 20190219 Won't Open Properly

### ISSUE THREAD

**Issue by KenLidd** [aferrero2707/gimp-appimage#28]
When attempting to open the latest GIMP AppImage update (Feb19, 2019 version) on Ubuntu 18.04, I get the following message:
There was an error parsing the menu definition from image-menu.xml: Failed to open file “/usr/local/gimp/share/gimp/2.0/menus/image-menu.xml”: No such file or directory
I have been using all other versions posted with no run problems. Can you please look into this fpr us?  Much appreciated.

**Comment by aferrero2707** [comment]
Hi! I will look into that later today. I suspect the issue has been introduced while adding support for the GTK3-based git master version...

**Comment by KenLidd** [comment]
Just loaded up the Feb 21st AppImage update (with plugins) and all worked very smoothly.  I noticed a version posted without plugins was labelled 2.99.1 - is this a typo.  I would have thought it is still 2,10.9?

**Comment by lxwndr** [comment]
@aferrero2707 I noticed that when renaming, the application is not executed.

For example, In:
"GIMP_AppImage-git-2.10.9-withplugins-20181227-x86_64.AppImage"

To (does not execute):
"GIMP 2.10.9.AppImage"

**Comment by aferrero2707** [comment]
@alexwender1 that's quite strange, the name of the file shouldn't matter. Have you tried to avoid spaces in the new name?

**Comment by aferrero2707** [comment]
@KenLidd 
> I noticed a version posted without plugins was labelled 2.99.1 - is this a typo.

No, it's not a typo, this is the experimental AppImage for the GTK3 version. I'm still fixing some issues with it, but should be functional very soon.

**Comment by lxwndr** [comment]
> @alexwender1 that's quite strange, the name of the file shouldn't matter. Have you tried to avoid spaces in the new name?

Right. No white space... the application runs. I have 4 other AppImage applications... all with white space... and they work.

Thanks for bringing GIMP to AppImage!

**Comment by KenLidd** [comment]
I notice that the last three or four AppImage updates have not included the plugins.  Is there a reason for this?  I really use the G'MIC plugin for a lot of our photo club work.

**Comment by aferrero2707** [comment]
@KenLidd 
> I notice that the last three or four AppImage updates have not included the plugins. Is there a reason for this? I really use the G'MIC plugin for a lot of our photo club work.

The plug-ins have been moved to an external repository: https://github.com/aferrero2707/gimp-plugins-collection/releases/tag/continuous
Installation instructions are given in the release page and here: https://mail.gnome.org/archives/gimp-developer-list/2019-April/msg00009.html

**Comment by KenLidd** [comment]
I think this is very good approach to the issue, especially if the plugins
don't change very often.  Some like G'MIC are continually updated though.
How can we tell when new versions are uploaded to the plugin repository
when no date is on them (unlike the GIMP AppImages which are clearly
marked)?
Thanks
Ken
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

       Ken Liddon        kenliddon@gmail.com       (613)476-2164

<><><><><><><><><><><><><><><><><><><><><><><><><><><>
