### ISSUE TITLE
mypaint brushes are not packaged in gimp appimage

### ISSUE THREAD

**Issue by Lvaskz** [aferrero2707/gimp-appimage#31]
Hi, I am using linuxmint 19.1, 64 bits, DE cinnamon
I am using GIMP_AppImage-git-2.10.9-withplugins-20190321-x86_64.AppImage, but it has not brushes from mypaint. Will you add it some day?

thanks 
gimp appimage is great

**Comment by aferrero2707** [comment]
@Lvaskz I will have a look at this during this week, and let you know here.

**Comment by Lvaskz** [comment]
any progress?

**Comment by aferrero2707** [comment]
@Lvaskz I am still trying to find a way to package the mypaint brushes and, more importantly, let GIMP find the packaged folder.

Meanwhile, did you try to install the brushes under `$HOME/.mypaint/brushes` as suggested [here](https://docs.gimp.org/2.10/en/gimp-tool-mypaint-brush.html)?

**Comment by aferrero2707** [comment]
@Lvaskz the latest AppImage packages have bundled mypaint brushes that should work out-of-the-box. Could you please check?

Thanks!

**Comment by Lvaskz** [comment]
Yep, Now is is working fine thanks
