### ISSUE TITLE
MIDI not working

### ISSUE THREAD

**Issue by lucmp** [aferrero2707/gimp-appimage#32]
I have Gimp 2.8 on Debian Stretch and MIDI works although I have to connect my controller to Gimp manually on a patch program such as Catia or Patchage. If I disable JACK and run on pure ALSA, then Catia won't work, only Patchage will, but I still can connect because there is a specific Gimp MIDI port/plug.

Runnning GIMP_AppImage-git-2.10.11-20190502-x86_64, there is no Gimp MIDI port/plug whatsoever and I can't have Gimp detect my controller.

**Comment by aferrero2707** [comment]
@lucmp MIDI support should be included in the most recent AppImages. Could you please test if it works for you?

Thanks!

**Comment by lucmp** [comment]
Hi. I just tested GIMP_AppImage-git-2.10.11-20190518-x86_64 and I can confirm that MIDI works. Thank you!
