### ISSUE TITLE
Please clean up the releases page.

### ISSUE THREAD

**Issue by simoniz0r** [aferrero2707/gimp-appimage#33]
It is very hard to find which release is the latest one in your repository, and next to impossible to automate finding the latest release.  Maybe you could create another release, upload all of the old builds to that, and only keep the latest release in the continuous tag?

**Comment by KenLidd** [comment]
It's now almost October and we have a very long list of old/interim versions of the GIMP.  I'd recommend that this page be trimmed at least every 2-3 months to clear out the clutter. Appreciate all you do for its development.

**Comment by aferrero2707** [comment]
@simoniz0r @KenLidd I have just now manually trimmed the release page, and from now on I will only keep the most recent version of the git snapshots (but I will keep few of the official releases).

Sorry for taking so long...

As for the automated finding of the latest release, that would be easy if I would drop the date from the file name, as the link would then stay the same. However, in this case it is not possible to easily find out when the package was created. Maybe a sidecar text file with build informations would be a good solution?

**Comment by KenLidd** [comment]
Thank you for looking at this.  I must say that I really like the date on
the file - sometimes the latest git snapshot just doesn't work very well
and I have to revert to the previous version - for instance the current
(Oct 3rd) GIMP version doesn't export jpg images - just a small black image
file is produced.  The previous, and all previous versions worked fine!
Cheers
Ken

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

       Ken Liddon        kenliddon@gmail.com       (613)476-2164

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

**Comment by aferrero2707** [comment]
There is a new package from today, could you check if Jpeg export works again? No idea if it is an upstream bug or something related to the AppImage itself...

**Comment by KenLidd** [comment]
Just on my way out, but I will try it out when I return later this
afternoon.
Ken

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

       Ken Liddon        kenliddon@gmail.com       (613)476-2164

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

**Comment by KenLidd** [comment]
Just tried the latest git snapshot (Oct 9th) and it saves jpg's fine - at
least in a very short test.  All appears fine.  If I find anything
different, I will let you know.
Thanks so much!
Ken

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

       Ken Liddon        kenliddon@gmail.com       (613)476-2164

<><><><><><><><><><><><><><><><><><><><><><><><><><><>
