### ISSUE TITLE
gimp-appimage Releases- Nothing for past month?

### ISSUE THREAD

**Issue by KenLidd** [aferrero2707/gimp-appimage#36]
I haven't seen any updated releases of the gimp-appimage 2.10.13 since the July 25th version.  Have I missed something or are people away on summer holidays?

**Comment by aferrero2707** [comment]
@KenLidd I had to update the BABL/GEGL build system to use meson/ninja. Now the automated 2.10.x builds are working again, except for the GTK3 version that requires a bit more work.

You can get a version from today from the usual continuous release page.

Thanks for the heads up!

**Comment by KenLidd** [comment]
Much appreciated - downloaded the updated build.  I now feel empowered - operating on the cutting edge!
