### ISSUE TITLE
GIMP 2.9.8 released!

### ISSUE THREAD

**Issue by ghost** [aferrero2707/gimp-appimage#4]
- https://www.gimp.org/news/2017/12/12/gimp-2-9-8-released/

Please, udate your AppImage!

**Comment by aferrero2707** [comment]
I am working on it, trying to automate the build process with Docker/Travis. I hope to have something new in few days...

**Comment by aferrero2707** [comment]
The automated build process with Docker/Travis is now set-up and working, and an updated AppImage package is now available from the "continuous" release.
