### ISSUE TITLE
G'MIC in GIMP Appimage

### ISSUE THREAD

**Issue by henry88g** [aferrero2707/gimp-appimage#40]
Hello - I've been trying the GIMP 2.99 Appimages with plugins, but can't see G'MIC in the filter dropdown window or the plugin explorer.  The plugins are in ~/.config/GIMP-Appimage/plug-ins.
Have I missed something?  I haven't triggered the desktop integration processes - could that be it?
I expect it's something simple, but ...   Any answer would be great.  

I'd also love to integrate xsane, would that mean rebuilding the Appimage, or should I be able to add the location of the xsane plugin from another GIMP installation to the plug-ins directories list in Preferences?  Or is this too simplistic?   Regards, Henry

**Comment by aferrero2707** [comment]
That's strange, I will have a look.

Concerning xsane, I doubt that an external plug-in would work. Also, in my experience such plug-ins that require low-level interactions with the system do not play well with the AppImage concept. I have been unsuccesfully struggling with gutenprint in the past...
Anyhow, I will look at that as well. Could you please open a new feature request issue for that, so that we can better track the progresses?

**Comment by henry88g** [comment]
Thanks very much for agreeing to look at this.

**Comment by henry88g** [comment]
For what it's worth, G'MIC appears and works fine in the 2.10 Appimage.  It just doesn't show up at all in the 2.99 Appimage.  The plugin folders shown in Preferences in both Appimages have the gmic_qt entry. Thoughts appreciated as and when - and Happy New Year to you.

**Comment by henry88g** [comment]
Any further ideas on the absence of G'MIC in the 2.99 Appimage?

**Comment by aferrero2707** [comment]
I didn't have time to look into that yet, sorry.

Could you eventually post the console messages you get when running the 2.99 appimage? There might be some indication of why GMIC doesn't work...

Thanks!

**Comment by KenLidd** [comment]
I've tried all sorts of things trying to move the plugins to recognized
directories but nothing appear to work.  I think the external plugins which
include G'Mic, Resynthesizer, NUFraw. LiquidRescale and PhFGimp - all get
put in an unrecognized .mount directory that doesn't show up in plugin
folder preferences. I tried to move them to a regular plugin folder in the
.config/GIMP-AppImage directory but that didn't seem to work.  I'll stay
with GIMP 2.15 for some time until these thing get resolved.
Regards
Ken
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

       Ken Liddon        kenliddon@gmail.com       (613)476-2164

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

**Comment by henry88g** [comment]
Nice to see that I'm not the only one with this issue.  It may be connected with existing (production) installation(s) - I don't understand much of the console output, but, here it is:

[Launch Gimp 2.99.txt](https://github.com/aferrero2707/gimp-appimage/files/4145225/Launch.Gimp.2.99.txt)

**Comment by henry88g** [comment]
Some of the content of the console file is irrelevant - looking for recently opened images, for example.  Still, there may be something there that someone can make sense of in the G'MIC context.  I do see:

Skipping potential plug-in '/home/henry/.config/GIMP-AppImage/2.99/plug-ins/xsane': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/usr/lib/gimp/2.0/plug-ins/xsane': plug-ins must be installed in subdirectories.

/usr/lib/gimp/2.0/plug-ins/gmic-gimp-qt/gmic-gimp-qt is a GIMP plug-in and must be run by GIMP to be used
GIMP-WARNING: gimp.bin: gimp_wire_read(): error

**Comment by henry88g** [comment]
Thanks, aferrero2707, for your response, by the way.

**Comment by henry88g** [comment]
For what it's worth, I've just now spotted:  https://gitlab.gnome.org/GNOME/gimp/issues/1649

**Comment by aferrero2707** [comment]
@KenLidd @henry88g the gimp issue you point out seems to confirm the main reason why I am not providing pre-compiled plug-ins for the 2.99 version: the plug-in interface is being re-factored, and the compatibility of existing plug-ins can break unexpectedly.

I prefer to focus on the 2.10.x version, for which (for example) I still need to fix the G'MIC macOS plugin...

**Comment by henry88g** [comment]
Understood.

**Comment by KenLidd** [comment]
I fully concur - I am quite happy to stay with 2.15 version.  Appreciate
your response.
Ken
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

       Ken Liddon        kenliddon@gmail.com       (613)476-2164

<><><><><><><><><><><><><><><><><><><><><><><><><><><>
