### ISSUE TITLE
GIMP 2.19 Releases

### ISSUE THREAD

**Issue by KenLidd** [aferrero2707/gimp-appimage#43]
I haven't seen any new post for the past couple of weeks.  Hope everyone is keeping safe in these troubling times. Just missing my weekly upgrade while I hibernate at home.

**Comment by aferrero2707** [comment]
@KenLidd all is fine from my side, thanks for asking! What about you?

The build of the 2.10.19 series has stopped working due to a recently introduced dependency on GLIB 2.56.2, which is not available as a package on CentOS7, therefore I am preparing a new docker image with GLIB2 compiled from sources.

Let's see if this is enough to get GIMP compile again...

Thanks for the heads up!

**Comment by aferrero2707** [comment]
@KenLidd the AppImages for the 2.10.19 series are back! In fact, GIMP requires more and more package versions that are not available in CentOS7, so I had to compile several more from sources. But now my Docker container is updated and the build system is running smoothly again.

I am now trying to fix the compilation of the GTK3 GIMP version.

Could you please confirm that the latest AppImage is working ok in your case?

Thanks!

**Comment by KenLidd** [comment]
Just downloaded and ran a test with the new 2.10.19 appimage release (March 23) and it works well on my system - Ubuntu 18.04.  I ran a few edits on images and all seemed to work as it should.  Appreciate the work you put in on this. I live in Canada and the corona virus has shut down all non-essential activities here - we are all house bound.  Had to suspend our photoclub sessions, although we are continuing with on-line activities to keep our photographers busy and creative. Stay safe!

**Comment by aferrero2707** [comment]
@KenLidd thanks for checking! The GTK3 builds are also up and running again.

I am locked at home as well, doing remote work and watching the world outside the window... it is really a "dystopic" feeling...

Closing this for now, feel free to re-open if things stop again and I do not see that...
