### ISSUE TITLE
GIMP_AppImage_2.10.19 Mar 28 Version Won't Run

### ISSUE THREAD

**Issue by KenLidd** [aferrero2707/gimp-appimage#45]
Just downloaded all the recent versions posted today.  The experimental 2.99.1 version opened fine, but neither of the 2.10.19 Mar 28 versions would open under Ubuntu 18.04. The Mar 23rd version runs fine.

**Comment by KenLidd** [comment]
I'm not sure where this stands, but I just see that you put up AppImage-2.99.1-20200401.  It will not execute under Ubuntu 18.04 (note the previous version 2.99.1-20200328 executes properly).  But I like to use the 2.10 versions, and the current posting 2.10.19-20200328 will not execute/open (the 2.10.19-20200323 works well). Hope all is well at you location in these horrific times.

**Comment by KenLidd** [comment]
Neither of the April 2nd AppImage versions - 2.10.19 nor 2.99.1 - will execute under Ubuntu 18.04. I'm still using the March 23 version of 2.10.19.

**Comment by KenLidd** [comment]
Ooops - my mistake, the April 2 AppImage for the 2.10.19 version does execute properly.  However, I can't get the 2.99.1 version to execute.

**Comment by mzannoni** [comment]
> I'm not sure where this stands, but I just see that you put up AppImage-2.99.1-20200401. It will not execute under Ubuntu 18.04 (note the previous version 2.99.1-20200328 executes properly). But I like to use the 2.10 versions, and the current posting 2.10.19-20200328 will not execute/open (the 2.10.19-20200323 works well). Hope all is well at you location in these horrific times.

I see the same thing on two machines (Ubuntu 18.04 and Manjaro 19.0.2).
I'll create a proper issue with details and standard output.
