### ISSUE TITLE
AppImage Updates for 2.10.19

### ISSUE THREAD

**Issue by KenLidd** [aferrero2707/gimp-appimage#51]
I haven't seen any updates posted since the 20200514 version.  I was used to seeing an updated version every week.  Can we expect an update soon? Thanks

**Comment by aferrero2707** [comment]
@KenLidd the automated builds have been fixed and resumed on the 5th of June, and they are now running regularly. Could you confirm that you can grab and use the latest package (tagged 2.10.21-20200612 at the time of writing)?

Thanks!

**Comment by KenLidd** [comment]
I am pleased to say that the latest 2.99 AppImage (2.99.1-20200618) is
running fine under Ubuntu 18.04. As always, appreciate your work in keeping
us up-to-date with this great piece of software.
Regards
Ken
<><><><><><><><><><><><><><><><><><><><><><><><><><><>

       Ken Liddon        kenliddon@gmail.com       (613)476-2164

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

**Comment by aferrero2707** [comment]
@KenLidd thanks for the confirmation! I will then close this issue.
