### ISSUE TITLE
git-2.99.1-20200618-withplugins crash

### ISSUE THREAD

**Issue by stevelcb** [aferrero2707/gimp-appimage#53]
ubuntu 18.04
Hi everyone
Good to see progress with the git now opening once again. Unfortunately calling colour > levels on a .jpg causes a crash.

Here is the bt:
https://drive.google.com/file/d/1BS-qPRR_k-OmwaSFvcpZfNumM_bEgWcc/view?usp=sharing

Cheers and thanks so much for the effort on the Appimage.
Steve

**Comment by KenLidd** [comment]
Steve - I just tried it and it worked fine with my version (AppImage
2.99.1-20200618) and Ubuntu 18.04. I opened a jpg image and then went to
Colours - Levels.  It operated normally on my machine.
Regards
Ken

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

       Ken Liddon        kenliddon@gmail.com       (613)476-2164

<><><><><><><><><><><><><><><><><><><><><><><><><><><>

**Comment by aferrero2707** [comment]
@stevelcb looks like a missing icon problem... I will try to investigate.

**Comment by aferrero2707** [comment]
Closing this issue as it is related to #54. The solution is to install the `gnome-icon-theme` system package.
