### ISSUE TITLE
Does not run on Ubuntu 14.04 

### ISSUE THREAD

**Issue by probonopd** [aferrero2707/gimp-appimage#6]
Does not run on Ubuntu 14.04:

```
/gimp.bin: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ././/lib/libexiv2.so.26)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6 on how to solve this.

References:
* https://github.com/AppImage/appimage.github.io/pull/98
* https://travis-ci.org/AppImage/appimage.github.io/builds/342694511#L772

**Comment by aferrero2707** [comment]
This should be fixed in the latest AppImage packages. Could you test the most recent one from [here](https://github.com/aferrero2707/gimp-appimage/releases/tag/continuous)?

Thanks!

**Comment by probonopd** [comment]
Actually, the script that does the testing picks the topmost one - could you remove or move the outdated ones? Thanks.

**Comment by aferrero2707** [comment]
Humm... that would not be very easy, as the files are named with the GIMP version and build date and github puts them in ascending order. Would it be difficult to modify your script and optionally pick the latest entry?

**Comment by probonopd** [comment]
Thanks, the latest version works. Added to https://appimage.github.io/GIMP/

**Comment by aferrero2707** [comment]
Cool! Thanks for your hard work in the AppImage business!!!

**Comment by aferrero2707** [comment]
By the way, you might be interested to know that the AppImage is automatically updated on a weekly basis using Travis cron jobs feature...
