### ISSUE TITLE
G'MIC-Qt fails to launch in Fedora 27

### ISSUE THREAD

**Issue by Mister-Dolus** [aferrero2707/gimp-appimage#7]
CLI output: 

file-jpeg:7347): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
Gtk-Message: Failed to load module "pk-gtk-module"
Calling custom execve(/tmp/.mount_PGcpv2/usr/lib/gimp/2.0/plug-ins/gmic_gimp_qt) function
adjusted_environment():
  filename="/tmp/.mount_PGcpv2/usr/lib/gimp/2.0/plug-ins/gmic_gimp_qt"
  appdir="/tmp/.mount_PGcpv2"
  appdir2="/tmp/.gimp-appimage"
execve(): old_execve=0x7fb82890b860
execve(): arr_len(new_envp)=105

(gmic_gimp_qt:7352): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(gmic_gimp_qt:7352): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
Gtk-Message: Failed to load module "pk-gtk-module"
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve ERR_free_strings
QSslSocket: cannot resolve sk_new_null
QSslSocket: cannot resolve sk_push
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot resolve SSLeay_version
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
/tmp/.mount_PGcpv2/usr/lib/gimp/2.0/plug-ins/gmic_gimp_qt: fatal error: Segmentation fault
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function ERR_free_strings
QMutex: destroying locked mutex

**Comment by aferrero2707** [comment]
It seems to be a problem of compatibility between thew OpenSSL library versions at compile- and run-time (see [for example [here](https://stackoverflow.com/questions/42094214/why-is-qsslsocket-working-with-qt-5-3-but-not-qt-5-7-on-debian-stretch)).

Could you check which version of OpenSSL you have on your Fedora 27 system?

Thanks!

**Comment by aferrero2707** [comment]
Could you check [the latest package](https://github.com/aferrero2707/gimp-appimage/releases/download/continuous/gimp-2.10.0-20180403_1029.glibc2.15-x86_64.AppImage)?
I have added libssl by hand in the bundle, which should fix the problem of missing symbols.

Thanks!

**Comment by Mister-Dolus** [comment]
Sorry for the delay... Yes, it seems to be working fine now, thank you.

**Comment by aferrero2707** [comment]
Thanks! I'm closing this for the moment, please feel free to re-open the issue if you encouter problems again.
